version: '3.8'
services:
  db:
    container_name: book-store-db
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - ../../docker-volumes/book-store-db:/var/lib/postgresql/data

  book-store-app:
    image: book-store-app:0.0.1
    container_name: book-store-app
    environment:
      DATABASE_HOSTNAME: db
    restart: on-failure
    ports:
      - 8002:8002
    depends_on:
      - db
