spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOSTNAME:localhost}:${DATABASE_PORT:5433}/book_store_db?createDatabaseIfNotExist=true
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect